[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios", "node-fetch"]

# Scheduled function: mobimatter-background
[[scheduled]]
  path = "/.netlify/functions/mobimatter-background"
  schedule = "0 */12 * * *"

# Scheduled function: recover-esims
[[scheduled]]
  path = "/.netlify/functions/recover-esims"
  schedule = "*/10 * * * *"

# Scheduled function: mobimatter-sync-scheduled
[[scheduled]]
  path = "/.netlify/functions/mobimatter-sync-scheduled-background"
  schedule = "0 3 * * *"
