[build]
  publish = "public"  # Set your publish directory, replace if different
  functions = "netlify/functions"  # Function directory

[[functions]]
  name = "mobimatter"
  path = "/.netlify/functions/mobimatter"
  timeout = 30
