[build]
  functions = "netlify/functions"

[[scheduled_functions]]
  name = "mobimatter-cron"
  schedule = "0 0 * * *"  # This cron expression means every day at midnight (UTC)
  function = "mobimatter-cron"
