[build]
functions = "netlify/functions"

[functions]
  [functions.timeout]
    default = 10  # Timeout in seconds

[[scheduled.functions]]
function = "mobimatter-background"
cron = "0 */12 * * *"


[[scheduled]]
  path = "/.netlify/functions/recover-esims"
  schedule = "*/10 * * * *"  # every 10 minutes
