[build]
 
  functions = "netlify/functions" # Define functions directory

[[functions]]
  name = "mobimatter"
  path = "/.netlify/functions/mobimatter"
  timeout = 30

# Optionally specify the publish directory if applicable
[build]
  publish = "public"

