[build]
  functions = "netlify-functions"

[[scheduled_functions]]
  name = "mobimatter-sync"
  schedule = "0 0 * * *"  # Run every day at midnight UTC
  function = "mobimatter"
  timeout = 900  # Max timeout of 900 seconds (15 minutes)
