[build]
functions = "netlify/functions"

[functions]
  [functions.timeout]
    default = 10  # Timeout in seconds

    [[scheduled.functions]]
function = "mobimatter-background"
cron = "0 */6 * * *" # runs every 6 hours

