[build]
  functions = "functions"

[functions]
  [functions.timeout]
    default = 10

# Optional security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self'"
    Strict-Transport-Security = "max-age=31536000"
