[build]
  functions = "netlify/functions" # Directory for functions
  publish = "public"  # Define the publish directory for static files

[functions]
  mobimatter = { 
    path = "/.netlify/functions/mobimatter"
    timeout = 30
  }
