[build]
functions = "netlify/functions"

[functions]
  [functions.timeout]
    default = 10  # Timeout in seconds

[[scheduled]]
  path = "/.netlify/functions/mobimatter-background"
  schedule = "0 */12 * * *"

[[scheduled]]
  path = "/.netlify/functions/recover-esims"
  schedule = "*/10 * * * *"
